project : main.o delete.o input.o print.o save.o update_database.o quit.o reverse.o autosave.o sort.o
	gcc -o project main.o delete.o input.o print.o save.o update_database.o quit.o reverse.o autosave.o sort.o


main	: main.c
	gcc -c  -o main.o main.c

delete	:delete.c
	gcc -c -o delete.o delete.c

reverse :reverse.c
	gcc -c -o reverse.o reverse.c

input 	:input.c
	gcc -c -o input.o input.c

print	:print.c
	gcc -c -o print.o print.c

save :save.c
	gcc -c -o save.o save.c

autosave :autosave.c
	gcc -c -o autosave.o autosave.c

sort :sort.c
	gcc -c -o sort.o sort.c

update_database	:update_database.c
		gcc -c -o update_database.o update_database.c


quit :quit.c
	gcc -c -o quit.o quit.c
